### ISSUE TITLE
[DOCS]: Push docker image to Google Artifact Registry

### ISSUE THREAD

**Issue by korawica** [dde-labs/self-docker#1]
```yaml
name: ci

on:
  workflow_dispatch:
  pull_request:
    branches:
      - dev
      - main

env:
  REGION: '<google-region-name>'
  SERVICE: '<google-artifact-registry-service-name>'

permissions:
  id-token: write
  contents: read

jobs:

  debug:
    runs-on: 'ubuntu-latest'
    steps:
      - run: |
          echo ${{ github.event.pull_request.head.ref }}
          echo ${{ github.event.pull_request.base.ref }}
          echo ${{ github.ref }}
      
      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo "$GITHUB_CONTEXT"

  build-dev:
    runs-on: 'ubuntu-latest'
    if: github.event.pull_request.base.ref == 'dev'
    env:
      PROJECT_ID: '<google-project-id>'
    steps:
      - uses: actions/checkout@v4

      - id: 'auth'
        name: 'Authenticate to Google Cloud'
        uses: google-github-actions/auth@v2
        with:
          service_account: <service-account>@<google=project-id>.iam.gserviceaccount.com
          workload_identity_provider: projects/<project-code>/locations/global/workloadIdentityPools/github/providers/<gh-organization-name>

      - name: "Set up Cloud SDK"
        uses: google-github-actions/setup-gcloud@v2

      - name: "Use gcloud CLI"
        run: |
          gcloud info

      - name: "List Account"
        run: |
          gcloud config list account --format "value(core.account)" 2> /dev/null

      - name: "Docker auth"
        run: |
          gcloud auth configure-docker ${{ env.REGION }}-docker.pkg.dev --quiet

      - name: "List Artifact Registry"
        continue-on-error: true
        run: |
          gcloud artifacts repositories list \
            --format 'value(name,format)' \
            --location=${{ env.REGION }}

      - name: 'Docker build'
        run: |
          DOCKER_IMAGE="${{ env.REGION }}-docker.pkg.dev/${{ env.PROJECT_ID }}/${{ env.SERVICE }}/${{ github.event.repository.name }}"
          DOCKER_TAG_SHA="${DOCKER_IMAGE}:${{ github.sha }}"
          DOCKER_TAG_LATEST="${DOCKER_IMAGE}:latest"
          docker build --tag "${DOCKER_TAG_SHA}" --tag "${DOCKER_TAG_LATEST}" -f .container/Dockerfile .
          docker image ls
          
          echo "DOCKER_IMAGE=${DOCKER_IMAGE}" >> $GITHUB_ENV
          echo "DOCKER_TAG_SHA=${DOCKER_TAG_SHA}" >> $GITHUB_ENV
          echo "DOCKER_TAG_LATEST=${DOCKER_TAG_LATEST}" >> $GITHUB_ENV

      - name: 'Docker push'
        run: |
          docker push "${DOCKER_TAG_SHA}"
          docker push "${DOCKER_TAG_LATEST}"
          
          docker image ls
          docker image rm -f $(docker image ls -a -q)

      - name: 'Docker pull'
        run: |
          docker pull "${DOCKER_TAG_LATEST}"
          docker run "${DOCKER_TAG_LATEST}"

  build-prod:
    runs-on: 'ubuntu-latest'
    if: github.event.pull_request.base.ref == 'main'
    env:
      PROJECT_ID: '<google-project-id>'
    steps:
      - uses: actions/checkout@v4

      - id: 'auth'
        name: 'Authenticate to Google Cloud'
        uses: google-github-actions/auth@v2
        with:
          service_account: <service-account>@<google=project-id>.iam.gserviceaccount.com
          workload_identity_provider: projects/<project-code>/locations/global/workloadIdentityPools/github/providers/<gh-organization-name>

      - name: "Set up Cloud SDK"
        uses: google-github-actions/setup-gcloud@v2

      - name: "Use gcloud CLI"
        run: |
          gcloud info

      - name: "List Account"
        run: |
          gcloud config list account --format "value(core.account)" 2> /dev/null

      - name: "Docker auth"
        run: |
          gcloud auth configure-docker ${{ env.REGION }}-docker.pkg.dev --quiet

      - name: "List Artifact Registry"
        continue-on-error: true
        run: |
          gcloud artifacts repositories list \
            --format 'value(name,format)' \
            --location=${{ env.REGION }}

      - name: 'Docker build'
        run: |
          DOCKER_IMAGE="${{ env.REGION }}-docker.pkg.dev/${{ env.PROJECT_ID }}/${{ env.SERVICE }}/${{ github.event.repository.name }}"
          DOCKER_TAG_SHA="${DOCKER_IMAGE}:${{ github.sha }}"
          DOCKER_TAG_LATEST="${DOCKER_IMAGE}:latest"
          docker build --tag "${DOCKER_TAG_SHA}" --tag "${DOCKER_TAG_LATEST}" -f .container/Dockerfile .
          docker image ls

          echo "DOCKER_IMAGE=${DOCKER_IMAGE}" >> $GITHUB_ENV
          echo "DOCKER_TAG_SHA=${DOCKER_TAG_SHA}" >> $GITHUB_ENV
          echo "DOCKER_TAG_LATEST=${DOCKER_TAG_LATEST}" >> $GITHUB_ENV

      - name: 'Docker push'
        run: |
          docker push "${DOCKER_TAG_SHA}"
          docker push "${DOCKER_TAG_LATEST}"

          docker image ls
          docker image rm -f $(docker image ls -a -q)

      - name: 'Docker pull'
        run: |
          docker pull "${DOCKER_TAG_LATEST}"
          docker run "${DOCKER_TAG_LATEST}"
```
